### ISSUE TITLE
multiple link proble

### ISSUE THREAD

**Issue by maxyonghuawei** [cgxeiji/CGx-InverseK#1]
Hi~
Thank you for your code and example. 
I wanna to know if this could be applied to multiple links robots like 6 ROF?
Thank you!

**Comment by cgxeiji** [comment]
Hi, I apologize for the late reply.

This library is optimized for a 3 link arm with a rotating base. I am afraid it cannot be used for multiple links.

**Comment by maxyonghuawei** [comment]
Thank you for your reply.
I see. Anyway, we finally decided to apply the Matalb toolkit instead and series communication.
Still Thank you for your help 😊.


________________________________
发件人: Eiji Onchi <notifications@github.com>
发送时间: Wednesday, August 21, 2019 12:54:11 PM
收件人: cgxeiji/CGx-InverseK <CGx-InverseK@noreply.github.com>
抄送: maxyonghuawei <yonghuawei@outlook.com>; Author <author@noreply.github.com>
主题: Re: [cgxeiji/CGx-InverseK] multiple link proble (#1)


Hi, I apologize for the late reply.

This library is optimized for a 3 link arm with a rotating base. I am afraid it cannot be used for multiple links.
