### ISSUE TITLE
Calculates the angles considering a specific approach angle

### ISSUE THREAD

**Issue by girmak7** [cgxeiji/CGx-InverseK#5]
hi i have a question about specific approach angle, what is the meaning of that?

**Comment by cgxeiji** [comment]
Imagine you want to pick a block with your gripper, but you can only approach it from above. Then you need to set a `phi` of 90 degrees from the horizontal plane so it always approach the block from above.

If you need to approach it from the side, then setting `phi` to 0 degrees will make the end effector position flat from the horizontal plane.

**Comment by cgxeiji** [comment]
I am closing this issue now, feel free to reopen it if you have more questions!
