### ISSUE TITLE
Question about _min_angle and _max_angle ?

### ISSUE THREAD

**Issue by Osamuyi97** [cgxeiji/CGx-InverseK#6]
How did you get your  min_angle and max_angle  in  the mylink.init(_length_, min_angle, max_angle_ ) function

**Comment by cgxeiji** [comment]
Those are the physical limits of your arm. For example, if you are using a 180 degree servo, they could be 0 to 180. But if you have a special arm shape that limits its range, then it could be 30 to 150 degrees.

I hope this answers your question.

**Comment by cgxeiji** [comment]
I am closing this issue now, feel free to reopen it if you have more questions!
